### ISSUE TITLE
Cassandra 2.x support

### ISSUE THREAD

**Issue by charsmith** [Netflix/aegisthus#15]
Cassandra moves on and we need to upgrade.  This task needs a little research and at least a dependency change.

**Comment by narsing3** [comment]
Can you guys confirm if there is support for commit log readers with Cass2X in c2_support Aegisthus yet. I dont see any changes but I just want to know if there are any plans to provide any such support in future. Advice is much appreciated.

**Comment by charsmith** [comment]
We haven't updated the commit log reader yet as we no longer use it in our pipeline.  @danielbwatson Can we merge the 2.0 pull request and then open the commit log reader as a separate issue?  I believe the change should be a matter of refactoring the deserialization into something we can use for commit logs as well.

@narsing3 The reason that we don't support it is that we thought it would allow us to do point of time pulls of a cluster without needing a flush.  Which is still true.  But the problem for us is that our clusters are write heavy so we would have to be constantly flushing out the commit logs to S3 (which is how we manage this flow).  So we have remained content to pull from the sstables themselves.

**Comment by danielbwatson** [comment]
@narsing3 Issue #40 is the issue for adding a commit log reader back to Aegisthus.  There are no immediate plans to work on this.

Closing this issue now that PR #39 has been merged in.  Thanks @danchia for all your help with this.
