### ISSUE TITLE
Composite row keys not read correctly

### ISSUE THREAD

**Issue by nishi1708** [Netflix/aegisthus#32]
Hi,

I have a wide row column family which has composite rows of type (UTF8Type,UTF8Type). I' using -D"aegisthus.keytype=CompositeType(UTF8Type, UTF8Type)" parameter while invoking MR job. Aegisthus is returning "e2" as key for following composite "e2e:abxdsdsd". its because of following line in SSTableRecordReader class, because ":" is treated as separator in composite keys.

key.set(json.substring(2, json.indexOf(':') - 1));

**Comment by danielbwatson** [comment]
I'm closing this issue because Aegisthus no longer passes data around in a JSON format internally so this error should no longer happen.  Also I'm going to add a note to the Enhancements section of the README about adding better support for CQL tables.
