### ISSUE TITLE
Using the new SSTable format

### ISSUE THREAD

**Issue by danchia** [Netflix/aegisthus#36]
@danielbwatson given that we're trying to deprecate the JSON output format, I wonder what's the best way for people to write downstream jobs that want to process data in a row manner?

It seems to be that there are two options:

(1) Run the same Mapper and Reducer used in aegisthus, but use a ChainReducer so that we can add a custom map stage after to do the application specific processing.

(2) The SSTables output by Aegisthus are actually special, since it's guaranteed that rows are non-overlapping and the columns are sorted in the right order. I'm wondering if we could expose this to a mapper in some smart way (and avoid the reduce step).

What do you think?

**Comment by danielbwatson** [comment]
I'm going to close this issue and add a reference to it in the Enhancement section of the README.
