### ISSUE TITLE
Use of rxJava without backpressure leads to excessive memory consumption

### ISSUE THREAD

**Issue by danchia** [Netflix/aegisthus#37]
SSTableColumnScanner creates an observable that produces data as fast as it can read from disk.
In SSTableRecordReader, we convert this observable to an iterator, which internally buffers data in a LinkedBlockingQueue of unbounded size.

If for whatever reason the mapper falls behind (e.g. doing a spill and sort), then the blockingQueue can grow to unbounded size. I've (somewhat hackily) fixed this in https://github.com/coursera/aegisthus/commit/807a0f44604f575f86e2a3ebd9a271531e522cdb by using a custom conversion toIterator that makes use of a bounded blocking queue. It's not very in the spirit of RxJava, however, as the toIterator observer blocks the observable when the queue is full.

**Comment by danielbwatson** [comment]
Again, good find @danchia Closing this as it was included in PR #39
