### ISSUE TITLE
Cassandra 3.0 support

### ISSUE THREAD

**Issue by danielbwatson** [Netflix/aegisthus#51]
I think I will be able to begin looking at this in around a month.

**Comment by mfocriteo** [comment]
Hi @danielbwatson We have been using aegisthus library for about an year in our project with cassandra 2.x and everything looked good. Currently we are planning to migrate to cassandra 3.x. 
Is it ok for you if we  contribute on this on a separate branch?
Can you make a rough estimation of how long it will take for one person to make the code compatible with 3.0?
Also can you provide some guidelines about what should be changed in the code?
Regards,
Marius.

**Comment by danielbwatson** [comment]
@mfocriteo That would be great if you wanted to contribute the changes to make Aegisthus work with Cassandra 3.x.  

I'm not sure how long it would take to make the changes.  Just changing the Cassandra dependency to 3.0.9 I see that 12 class have compile errors.  It looks like OnDiskAtom has been renamed or moved, that will probably be the largest change.

As far as what to be careful about I think that SSTableColumnScanner is the most difficult because you have to support reading from multiple Cassandra versions.  Breaking that into separate files per version might make things clearer as long as we can keep the versions from drifting apart.

**Comment by danielbwatson** [comment]
Closing all issues since the project is archived.
