### ISSUE TITLE
how i creating cassandra sstable from a hive table？

### ISSUE THREAD

**Issue by zhaiyuyong** [Netflix/aegisthus#53]

**Comment by bniculescu** [comment]
You can read data from Hive, and then drop it into offline SSTables with CQLSSTableWriter and then bulk load them into Cassandra with sstableloader. For an example with CQLSSTableWriter & sstableloader have a look at the Cassandra official documentation : http://www.datastax.com/dev/blog/using-the-cassandra-bulk-loader-updated

**Comment by danielbwatson** [comment]
Closing this because Aegisthus only works in the opposite direction, Cassandra to Hive.

To go from Hive to Cassandra I would use the suggestion from @bniculescu or https://github.com/datastax/spark-cassandra-connector depending on your preferences and what fits in better with your stack.
