### ISSUE TITLE
Deleted columns reach output in case of non-deleted rows.

### ISSUE THREAD

**Issue by rzvoncek** [Netflix/aegisthus#7]
Some versions of Cassandra (1.2 for sure, 1.1 possibly) initialize the "deleted at" field for rows in SSTables to Long.MIN_VALUE (which is a very large negative number).

When the CassReducer checks for deleted columns, it is comparing column deletion timestamps to the row deletion timestamp. In case the row has not been deleted, its "deleted at" will be Long.MIN_VALUE and the appropriate [condition] [1] will not hold (signed negative number deletedAt is not larger than column deletion time ts).

This way, deleted columns will find their way to the output.

[1]: https://github.com/Netflix/aegisthus/blob/master/aegisthus-hadoop/src/main/java/com/netflix/aegisthus/mapred/reduce/CassReducer.java#L95

**Comment by danielbwatson** [comment]
Closing this as I believe Aegisthus now removes the deleted columns See https://github.com/Netflix/aegisthus/blob/1343de5b389c5a846d8509102078e3ca0680bedf/aegisthus-hadoop/src/main/java/com/netflix/aegisthus/mapreduce/CassSSTableReducer.java#L176

If you don't feel this is sufficient we can add an entry to the enhancements section of the README referencing this request.
