### ISSUE TITLE
Handling very large sstables

### ISSUE THREAD

**Issue by bvanberg** [Netflix/aegisthus#9]
I am attempting to run aegisthus against a Priam backup containing some very large sstables (~200GB in size). Being that these files are snappy compressed (in addition to the Cassandra snappy compression) and we are using Cassandra 1.2 I'm currently using the code on the coursera fork.  I'm running into problems with this as it takes a very long time (3+ hours) to handle these very large files. Aegisthus appears to expect sstables which haven't been double compressed by Priam, and doesn't appear to split the files if the -CompressionInfo.db files are available. 

Questions:

1. Do you guys use Aegisthus with similarly large sstables? 
2. Do you get any splitting on sstables that have the internal Cassandra snappy data? (i.e. -CompressionInfo.db files are available)

**Comment by danielbwatson** [comment]
This would still be a nice enhancement.  I am closing the issue and adding a reference to this in the Enhancements section of the README.
